name: Quality Gate (Example)

on:
  pull_request:
  workflow_dispatch:

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run unit and contract tests
        run: |
          pytest tests/unit tests/contract -q

      - name: Run compile checks
        run: |
          python -m compileall .
